<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statement – {{ $user->name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 12px; margin-bottom: 20px; }
        .bank-name { font-size: 18px; font-weight: bold; color: #4f46e5; }
        .subtitle { font-size: 10px; color: #666; margin-top: 4px; }
        .client-info { margin-bottom: 20px; }
        .client-info table { width: 100%; }
        .client-info td { padding: 2px 8px 2px 0; }
        .label { color: #666; }
        .period { margin-bottom: 16px; font-size: 10px; color: #666; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { text-align: left; padding: 8px 6px; background: #f3f4f6; font-size: 9px; text-transform: uppercase; }
        table.data td { padding: 6px; border-bottom: 1px solid #e5e7eb; }
        table.data .amount { text-align: right; }
        .credit { color: #059669; }
        .debit { color: #dc2626; }
        .totals { margin-top: 24px; padding-top: 12px; border-top: 2px solid #e5e7eb; }
        .totals table { width: 100%; max-width: 320px; margin-left: auto; }
        .totals td { padding: 4px 8px; }
        .totals .label { font-weight: bold; }
        .footer { margin-top: 28px; font-size: 9px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="bank-name">Priority Bank</div>
        <div class="subtitle">Save together. Grow together.</div>
    </div>

    <div class="client-info">
        <table>
            <tr><td class="label">Account holder</td><td>{{ $user->name }}</td></tr>
            <tr><td class="label">Email</td><td>{{ $user->email }}</td></tr>
            <tr><td class="label">Phone</td><td>{{ $user->phone ?? 'N/A' }}</td></tr>
            <tr><td class="label">Statement date</td><td>{{ now()->format('F d, Y') }}</td></tr>
            <tr><td class="label">Net balance</td><td>GHS {{ number_format($user->net_balance, 2) }}</td></tr>
        </table>
    </div>

    <div class="period">
        @if($startDate || $endDate)
            Period: {{ $startDate ? $startDate->format('m/d/Y') : '—' }} to {{ $endDate ? $endDate->format('m/d/Y') : '—' }}
        @else
            Period: All transactions
        @endif
    </div>

    <table class="data">
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Description</th>
                <th>Category / Source</th>
                <th class="amount">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($entries as $entry)
            <tr>
                <td>{{ $entry->date->format('M d, Y') }}</td>
                <td>{{ $entry->type === 'income' ? 'Credit' : 'Debit' }}</td>
                <td>{{ $entry->description ?: '—' }}</td>
                <td>{{ $entry->category }}</td>
                <td class="amount {{ $entry->type === 'income' ? 'credit' : 'debit' }}">
                    {{ $entry->type === 'income' ? '+' : '-' }}GHS {{ number_format($entry->amount, 2) }}
                </td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align:center;padding:16px;">No statement entries in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="totals">
        <table>
            <tr><td class="label">Total credits</td><td class="amount credit">GHS {{ number_format($totalCredits, 2) }}</td></tr>
            <tr><td class="label">Total debits</td><td class="amount debit">GHS {{ number_format($totalDebits, 2) }}</td></tr>
            <tr><td class="label">Net balance</td><td class="amount">{{ $netBalance >= 0 ? '' : '-' }}GHS {{ number_format(abs($netBalance), 2) }}</td></tr>
        </table>
    </div>

    <div class="footer">
        This statement was generated by Priority Bank. For queries, contact your branch or support.
        <br><br>
        Monthly legacy rollup lines show one total per period; itemized diary text for those entries is stored in Notes on the corresponding transaction in Priority Bank (Transactions → open by ID).
    </div>
</body>
</html>
